name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish-to-github:
    name: Publish to Github
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: vtt-wod-book-parser-${{ matrix.os }}
          path: target/vtt-wod-book-parser-${{ matrix.os }}
      - name: Package Artifacts - Full
        run: |
          src=$(pwd)
          stage=$(mktemp -d)
          suffix=""
          osName=""
          case "${{ matrix.os }}" in
              ubuntu-latest)
                osName="linux"
                ;;
              macos-latest)
                osName="macos"
                ;;
              windows-latest)
                osName="windows"
                suffix=".exe"
                ;;
              *)
                osName="unknown"
                suffix=".unknown"
                ;;
          esac
          cp target/vtt-wod-book-parser-${{ matrix.os }} $stage/vtt-wod-book-parser-$osName-x64$suffix
          cd $stage
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          ARCHIVE_SUFFIX=""
          COMPRESSION_COMMAND=""
          if [[ "$osName" == "windows" ]]; then
            ARCHIVE_SUFFIX="zip"
            COMPRESSION_COMMAND="zip -r"
          else
            ARCHIVE_SUFFIX="tgz"
            COMPRESSION_COMMAND="tar czf"
          fi
          
          ASSET_NAME="vtt-wod-book-parser-$osName-$RELEASE_VERSION.$ARCHIVE_SUFFIX"
          ASSET_PATH="$src/$ASSET_NAME"
          CHECKSUM_PATH="$ASSET_PATH.sha256"
          echo "ASSET_PATH=$ASSET_PATH" >> $GITHUB_ENV
          echo "CHECKSUM_PATH=$CHECKSUM_PATH" >> $GITHUB_ENV
          $COMPRESSION_COMMAND $ASSET_PATH *
          
          cd $src
          sha256sum $ASSET_NAME > $CHECKSUM_PATH

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            ${{ env.ASSET_PATH }}
            ${{ env.CHECKSUM_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}